"""Add certificate type and decision

Revision ID: 773b83dc9064
Revises: 641a88806884
Create Date: 2026-03-15 23:01:49.681466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '773b83dc9064'
down_revision: Union[str, None] = '641a88806884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate_decisions',
    sa.Column('decision_number', sa.String(length=100), nullable=False),
    sa.Column('decision_date', sa.Date(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificate_types',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('field_schema', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    
    # Insert a default certificate type for existing templates
    import uuid
    default_type_id = str(uuid.uuid4())
    op.execute(
        f"INSERT INTO certificate_types (id, code, name, description, field_schema, created_at, updated_at) "
        f"VALUES ('{default_type_id}', 'general', 'General Certificate', 'Default type for existing templates', '{{}}', now(), now())"
    )

    op.add_column('certificates', sa.Column('decision_id', sa.UUID(), nullable=True))
    op.add_column('certificates', sa.Column('registry_number', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'certificates', 'certificate_decisions', ['decision_id'], ['id'])
    
    # 1. Add as nullable
    op.add_column('templates', sa.Column('certificate_type_id', sa.UUID(), nullable=True))
    
    # 2. Update existing rows
    op.execute(f"UPDATE templates SET certificate_type_id = '{default_type_id}'")
    
    # 3. Make it NOT NULL
    op.alter_column('templates', 'certificate_type_id', nullable=False)
    
    op.create_foreign_key(None, 'templates', 'certificate_types', ['certificate_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'templates', type_='foreignkey')
    op.drop_column('templates', 'certificate_type_id')
    op.drop_constraint(None, 'certificates', type_='foreignkey')
    op.drop_column('certificates', 'registry_number')
    op.drop_column('certificates', 'decision_id')
    op.drop_table('certificate_types')
    op.drop_table('certificate_decisions')
    # ### end Alembic commands ###
