"""add registry_start_number to batch

Revision ID: aea62e1a69fd
Revises: 773b83dc9064
Create Date: 2026-03-17 23:20:32.919386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aea62e1a69fd'
down_revision: Union[str, None] = '773b83dc9064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate_batches', sa.Column('decision_id', sa.UUID(), nullable=True))
    op.add_column('certificate_batches', sa.Column('registry_start_number', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'certificate_batches', 'certificate_decisions', ['decision_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'certificate_batches', type_='foreignkey')
    op.drop_column('certificate_batches', 'registry_start_number')
    op.drop_column('certificate_batches', 'decision_id')
    # ### end Alembic commands ###
